### ISSUE TITLE
[BUG] Los animales que menos participaron

### ISSUE THREAD

**Issue by micardona96** [micardona96/The-Animal-Show#2]
Cuando se ejecuta el nuevo teste, largo de N = 20, M = 6, K = 10 , se obtienen resultados extraños, en el análisis de:  **los animales que menos participaron** aparecen todos los animales. ver la imagen,

ejecutar el comando: 
`> py main.py large`

Se obtiene 
![image](https://user-images.githubusercontent.com/37484798/82017966-e52e0980-9649-11ea-9a62-c4e1421c9b50.png)

Probado en windows 10 con Intel

**Comment by micardona96** [comment]
mismo error en linux

https://repl.it/@MiguelCardona/The-Animal-Show

**Comment by tavo1998** [comment]
Errores de lógica solucionados
