### ISSUE TITLE
Error en los resultados [Resuelto]

### ISSUE THREAD

**Issue by micardona96** [micardona96/The-Animal-Show#4]
Teniendo en cuenta la modificación en el entendimiento de la función  **timeit()**

> El método timeit() ejecuta la instrucción de configuración una vez, luego ejecuta la instrucción primaria repetidamente y  **devuelve la cantidad de tiempo que pasa desde el primer llamado hasta el final**. El argumento de timeit() controla cuántas veces ejecutar la declaración; el valor predeterminado es 1,000,000.

me conllevo a el análisis de los resultados, Que pasa con la repetición del algoritmo burbuja 200 veces, en la primera iteración del algoritmo burbuja, se organizan, y para la segunda iteración el input array ya fue modificado y ordenado, el algoritmo burbuja no demorara N², por que su entrada ya está ordenada, entonces para los 199 casos la complejidad de burbuja será N.

``` python
arrayNumeros = [randint(1, int(sys.argv[1])) for i in range(int(sys.argv[1]))]

. . .

resultado3 = timeit('sortNxN(arrayNumeros)', globals=globals(), number=200)
print('Solución O(N²) \t \t' + str(resultado3 * 1000) + '\n')
``` 

Esto error de paso por valor, sólo afecta a este algoritmo ya que el **QuickSort** usa un pivote aleatorio, y el **CountingSort** no ordena por comparaciones.

Además teniendo en cuenta el verdadero funcionamiento de **timeit()**, se dispone a promediar de forma manual los resultados. y contemplando su respuesta en Segundos.

> Se aumentó 1000 repeticiones, al mismo tiempo en que se divide el tiempo total por 1000

``` python
resultado3 = timeit(
    'sortNxN([randint(1, int(sys.argv[1])) for i in range(int(sys.argv[1]))])', globals=globals(), number=1000)
print('Solución O(N²) \t \t' + str(resultado3) + '\n')
``` 
Resultados concluyentes 

``` sh
> python main.py run-test 500

--- RESULTADOS DEL TEST (seconds) ---
Array size in test: 500
Solución O(N)           1.7864567999999998
Solución O(N log N)     3.4915547
Solución O(N²)          41.3534041

``` 

``` sh
> python main.py run-test  84

--- RESULTADOS DEL TEST (seconds) ---
Array size in test: 84
Solución O(N)           0.1958164
Solución O(N log N)     0.4710505
Solución O(N²)          1.1376020000000002

```

**Comment by micardona96** [comment]
@tavo1998 Esto podría estar afectando también el funcionamiento en las llamadas a los procedimientos NxN en las clases espectaculo, parte y escena?

**Comment by tavo1998** [comment]
En el algoritmo burbuja sólo existe una comparación, y el número en que itera siempre es el mismo, en el caso de que el arreglo esté ordenado, la comparación se realiza pero nunca será True, evitando entonces hacer los cambios respectivos, esto podría afectar brevemente los tiempos de ejecución, sin embargo no es una respuesta muy clara.

**Comment by micardona96** [comment]
![image](https://user-images.githubusercontent.com/37484798/82126384-012cca80-9772-11ea-88ae-efe74d6a55ff.png)

**Comment by micardona96** [comment]
![image](https://user-images.githubusercontent.com/37484798/82126397-1ace1200-9772-11ea-8d97-79c098ae9e64.png)
